language: node_js
node_js: ["13"]
before_install:
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Travis CI Deployment Bot"
script:
- npm install
- npm run build
after_success:
- cd build
- echo "sl.45gfg9.net" >CNAME
- git init; git add .; git commit -m "Deploy"
- git push -fq https://45gfg9:${GITHUB_TOKEN}@github.com/45gfg9/MCBBS-SLConverter.git master:gh-pages
